language: python
python:
    - "3.6"
    - "3.7"
install: 
    - pip install tox
    - pip install -r docs/requirements.txt
script:
    - flake8 src
    - tox
    - "sphinx-build -WT -b dummy -d docs docs docs/_build/html"
